// <auto-generated />
using System;
using CodeBlue.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeBlue.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206095806_AddClaimLinks")]
    partial class AddClaimLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeBlue.Data.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AddressKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("AnimalsPresent")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GateCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("LegacyRecordId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("OriginalInstallerDealer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartupDate")
                        .HasColumnType("date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CodeBlue.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeBlue.Data.Entities.WarrantyClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("FailureDate")
                        .HasColumnType("date");

                    b.Property<string>("IdSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image1Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("LegacyRecordId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("OriginalInstallationDate")
                        .HasColumnType("date");

                    b.Property<string>("OriginalInstallerDealer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("RepairDate")
                        .HasColumnType("date");

                    b.Property<string>("ServiceRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimNumber");

                    b.HasIndex("CustomerId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WarrantyClaims");
                });

            modelBuilder.Entity("CodeBlue.Data.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AnimalsPresent")
                        .HasColumnType("bit");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuilderCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuilderContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuilderContactFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuilderContactLast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuilderContactMiddle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuilderContactTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuilderEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuilderPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegacyRecordId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ScheduledServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("ServiceAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceContactFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceContactLast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceContactMiddle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceContactTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ServiceLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("ServiceLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("ServicePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ServiceStartupDate")
                        .HasColumnType("date");

                    b.Property<string>("ServiceState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceStreet1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceStreet2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceZip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Space")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("CodeBlue.Data.Entities.WarrantyClaim", b =>
                {
                    b.HasOne("CodeBlue.Data.Entities.Customer", "Customer")
                        .WithMany("WarrantyClaims")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CodeBlue.Data.Entities.WorkOrder", "WorkOrder")
                        .WithMany("WarrantyClaims")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("CodeBlue.Data.Entities.WorkOrder", b =>
                {
                    b.HasOne("CodeBlue.Data.Entities.Customer", "Customer")
                        .WithMany("WorkOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CodeBlue.Data.Entities.Customer", b =>
                {
                    b.Navigation("WarrantyClaims");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("CodeBlue.Data.Entities.WorkOrder", b =>
                {
                    b.Navigation("WarrantyClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
